# Project Euler Problem #2
#  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


import math

# first make the terms until we get to 4e6

x1 = 1
x2 = 2
xsum = x1 + x2
temp = 2 # because the first value is 2
val = 4000000
while xsum < val:
	if xsum % 2 == 0:
		temp = temp+xsum
		# print(xsum)
	x1 = x2
	x2 = xsum
	xsum = x1 + x2

print(temp)