# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

import pdb

count = 1
val0 = 1
tri = 0
# loop until we find a value with n divisors
while True:

	tri = tri+val0

	# find the divisors of the triangle
	count = 0
	n = tri
	# print(tri)
	print(tri)
	div = []
	for i in range(1,n+1):
		if n % i == 0:
			div.append(i)
			count += 1
			n = n/i
	print(div)
	# print('divisors = '+str(count))

	val0 += 1
	if val0 > 10:
		break


